# docker-compose.yml
version: '3'
services:
  jenkins:
    image: booooza/jenkins-docker
    ports:
      - "8080:8080"
    build:
        context: .
        dockerfile: jenkins/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock