node {
    def nodeHome = tool name: 'node', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
    env.PATH = "${nodeHome}/bin:${env.PATH}"

    stage('Clone code repository') {
        checkout scm
    }

    stage('Install React Application') {
        sh 'cd app && npm install' 
    }  

    stage('Build React Bundle') {
        sh 'cd app && npm run build'
    }

    withEnv(['CI=true']) {
        stage('Test React Application') {
            sh 'cd app && npm test' 
        }  
    }
    withCredentials([string(credentialsId: 'githubtoken', variable: 'TOKEN')]) {
        stage('Deploy to Github Pages') {
            sh '''
            cd app 
            git remote rm origin
            git remote add origin https://booooza:$TOKEN@github.com/booooza/cicd-jenkins-react-demo.git
            npm run deploy
            '''
        }
    }
}