node {
    def nodeHome = tool name: 'node', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
    env.PATH = "${nodeHome}/bin:${env.PATH}"

    stage('Clone code repository') {
        checkout scm
        slackSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
    }

    stage('Install React Application') {
        sh 'cd app && npm install' 
    }  

    stage('Build React Bundle') {
        sh 'cd app && npm run build'
    }

    withEnv(['CI=true']) {
        stage('Test React Application') {
            sh 'cd app && npm test' 
            slackSend "Build finished - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }  
    }
}